"""Catálogo de 50 APIs públicas gratuitas usadas por Mente Maestra.

La mayoría no requiere clave. Las que sí (NASA DEMO_KEY) vienen con clave pública de demostración.
Respeta rate limits y User-Agent. No uses estos endpoints para abuso comercial masivo.
"""

APIS = [
    {
        "id": 1,
        "name": "Open-Meteo Forecast",
        "category": "clima",
        "auth": "none",
        "docs": "https://open-meteo.com/en/docs",
        "url": "https://api.open-meteo.com/v1/forecast",
        "params": {"latitude": 29.76, "longitude": -95.37, "current_weather": True, "daily": "temperature_2m_max,temperature_2m_min,precipitation_sum", "forecast_days": 7, "timezone": "auto"},
        "uso": "Pronóstico del tiempo 7 días. Base para modelos de demanda, logística y energía.",
    },
    {
        "id": 2,
        "name": "Open-Meteo Air Quality",
        "category": "clima",
        "auth": "none",
        "docs": "https://open-meteo.com/en/docs/air-quality-api",
        "url": "https://air-quality-api.open-meteo.com/v1/air-quality",
        "params": {"latitude": 29.76, "longitude": -95.37, "current": "pm10,pm2_5,us_aqi"},
        "uso": "Calidad del aire para salud, HVAC y predicción ambiental.",
    },
    {
        "id": 3,
        "name": "wttr.in",
        "category": "clima",
        "auth": "none",
        "docs": "https://github.com/chubin/wttr.in",
        "url": "https://wttr.in/Houston?format=j1",
        "params": {},
        "uso": "Clima actual y pronóstico en JSON sin clave.",
    },
    {
        "id": 4,
        "name": "Sunrise Sunset",
        "category": "clima",
        "auth": "none",
        "docs": "https://sunrise-sunset.org/api",
        "url": "https://api.sunrise-sunset.org/json",
        "params": {"lat": 29.76, "lng": -95.37, "formatted": 0},
        "uso": "Amanecer/atardecer para energía solar y ciclos circadianos.",
    },
    {
        "id": 5,
        "name": "USGS Earthquakes",
        "category": "ciencia",
        "auth": "none",
        "docs": "https://earthquake.usgs.gov/fdsnws/event/1/",
        "url": "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_month.geojson",
        "params": {},
        "uso": "Sismos significativos del mes. Señal de riesgo geológico.",
    },
    {
        "id": 6,
        "name": "Nominatim OpenStreetMap",
        "category": "geo",
        "auth": "none",
        "docs": "https://nominatim.org/release-docs/latest/api/Search/",
        "url": "https://nominatim.openstreetmap.org/search",
        "params": {"q": "Houston, Texas", "format": "json", "limit": 1},
        "uso": "Geocoding gratuito. Convierte ciudad a lat/lon para pronósticos.",
        "headers": {"User-Agent": "MenteMaestra/1.0 (github.com/rmpsorva/mente-maestra)"},
    },
    {
        "id": 7,
        "name": "ip-api",
        "category": "geo",
        "auth": "none",
        "docs": "https://ip-api.com/docs",
        "url": "http://ip-api.com/json/",
        "params": {},
        "uso": "Geolocalización por IP para contexto local automático.",
    },
    {
        "id": 8,
        "name": "ipify",
        "category": "geo",
        "auth": "none",
        "docs": "https://www.ipify.org/",
        "url": "https://api.ipify.org",
        "params": {"format": "json"},
        "uso": "IP pública del entorno de ejecución.",
    },
    {
        "id": 9,
        "name": "Zippopotam",
        "category": "geo",
        "auth": "none",
        "docs": "https://www.zippopotam.us/",
        "url": "https://api.zippopotam.us/us/77002",
        "params": {},
        "uso": "Código postal a ciudad/estado (Houston downtown).",
    },
    {
        "id": 10,
        "name": "REST Countries",
        "category": "datos",
        "auth": "none",
        "docs": "https://restcountries.com/",
        "url": "https://restcountries.com/v3.1/name/united%20states",
        "params": {"fields": "name,capital,population,currencies,region,area"},
        "uso": "Perfil de país para modelos macro y contexto geopolítico.",
    },
    {
        "id": 11,
        "name": "World Bank GDP",
        "category": "economia",
        "auth": "none",
        "docs": "https://datahelpdesk.worldbank.org/knowledgebase/articles/889392",
        "url": "https://api.worldbank.org/v2/country/USA/indicator/NY.GDP.MKTP.CD",
        "params": {"format": "json", "per_page": 5},
        "uso": "PIB histórico. Feature macro para forecasting económico.",
    },
    {
        "id": 12,
        "name": "World Bank Inflation",
        "category": "economia",
        "auth": "none",
        "docs": "https://datahelpdesk.worldbank.org/knowledgebase/articles/889392",
        "url": "https://api.worldbank.org/v2/country/USA/indicator/FP.CPI.TOTL.ZG",
        "params": {"format": "json", "per_page": 5},
        "uso": "Inflación anual. Señal para pronósticos de precios.",
    },
    {
        "id": 13,
        "name": "Frankfurter ECB",
        "category": "finanzas",
        "auth": "none",
        "docs": "https://www.frankfurter.app/docs/",
        "url": "https://api.frankfurter.app/latest",
        "params": {"from": "USD", "to": "EUR,MXN,COP,GBP"},
        "uso": "Tipos de cambio oficiales BCE. Pronóstico FX y conversión.",
    },
    {
        "id": 14,
        "name": "Open Exchange Rates mirror",
        "category": "finanzas",
        "auth": "none",
        "docs": "https://www.exchangerate-api.com/docs/free",
        "url": "https://open.er-api.com/v6/latest/USD",
        "params": {},
        "uso": "Canasta amplia de tipos de cambio vs USD.",
    },
    {
        "id": 15,
        "name": "CoinGecko Simple Price",
        "category": "crypto",
        "auth": "none",
        "docs": "https://docs.coingecko.com/reference/simple-price",
        "url": "https://api.coingecko.com/api/v3/simple/price",
        "params": {"ids": "bitcoin,ethereum,solana", "vs_currencies": "usd", "include_24hr_change": "true"},
        "uso": "Precios crypto en tiempo real. Señal de riesgo-apetito.",
    },
    {
        "id": 16,
        "name": "CoinGecko Markets",
        "category": "crypto",
        "auth": "none",
        "docs": "https://docs.coingecko.com/reference/coins-markets",
        "url": "https://api.coingecko.com/api/v3/coins/markets",
        "params": {"vs_currency": "usd", "ids": "bitcoin", "sparkline": "false"},
        "uso": "Market cap, volumen y supply para modelos de mercado.",
    },
    {
        "id": 17,
        "name": "CoinCap Assets",
        "category": "crypto",
        "auth": "none",
        "docs": "https://docs.coincap.io/",
        "url": "https://api.coincap.io/v2/assets",
        "params": {"limit": 5},
        "uso": "Top criptoactivos como fuente alternativa de precios.",
    },
    {
        "id": 18,
        "name": "Wikipedia Summary",
        "category": "conocimiento",
        "auth": "none",
        "docs": "https://en.wikipedia.org/api/rest_v1/",
        "url": "https://en.wikipedia.org/api/rest_v1/page/summary/Artificial_intelligence",
        "params": {},
        "uso": "Resumen enciclopédico para grounding de IA.",
    },
    {
        "id": 19,
        "name": "Wikipedia Search",
        "category": "conocimiento",
        "auth": "none",
        "docs": "https://www.mediawiki.org/wiki/API:Main_page",
        "url": "https://en.wikipedia.org/w/api.php",
        "params": {"action": "opensearch", "search": "forecasting", "limit": 5, "format": "json"},
        "uso": "Búsqueda rápida de conceptos para el cerebro.",
    },
    {
        "id": 20,
        "name": "OpenAlex Works",
        "category": "investigacion",
        "auth": "none",
        "docs": "https://docs.openalex.org/",
        "url": "https://api.openalex.org/works",
        "params": {"search": "time series forecasting", "per_page": 3},
        "uso": "250M+ papers. Alimenta RAG y estado del arte de modelos.",
        "headers": {"User-Agent": "MenteMaestra/1.0 (mailto:rmpaicom@gmail.com)"},
    },
    {
        "id": 21,
        "name": "Crossref Works",
        "category": "investigacion",
        "auth": "none",
        "docs": "https://www.crossref.org/documentation/retrieve-metadata/rest-api/",
        "url": "https://api.crossref.org/works",
        "params": {"query": "artificial intelligence forecasting", "rows": 3},
        "uso": "Metadatos DOI y citas para entrenamiento y bibliografía.",
        "headers": {"User-Agent": "MenteMaestra/1.0 (mailto:rmpaicom@gmail.com)"},
    },
    {
        "id": 22,
        "name": "arXiv",
        "category": "investigacion",
        "auth": "none",
        "docs": "https://info.arxiv.org/help/api/index.html",
        "url": "http://export.arxiv.org/api/query",
        "params": {"search_query": "all:forecasting+AND+all:neural", "start": 0, "max_results": 3},
        "uso": "Preprints de ML. Fuente viva para desarrollar IA.",
    },
    {
        "id": 23,
        "name": "PubMed E-utilities",
        "category": "investigacion",
        "auth": "none",
        "docs": "https://www.ncbi.nlm.nih.gov/books/NBK25501/",
        "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi",
        "params": {"db": "pubmed", "term": "machine learning prognosis", "retmode": "json", "retmax": 5},
        "uso": "Literatura biomédica para IA de salud.",
    },
    {
        "id": 24,
        "name": "Semantic Scholar",
        "category": "investigacion",
        "auth": "none",
        "docs": "https://api.semanticscholar.org/api-docs/",
        "url": "https://api.semanticscholar.org/graph/v1/paper/search",
        "params": {"query": "time series foundation models", "limit": 3, "fields": "title,year,citationCount,url"},
        "uso": "Papers + citas + recomendaciones semánticas.",
    },
    {
        "id": 25,
        "name": "NASA APOD",
        "category": "ciencia",
        "auth": "demo_key",
        "docs": "https://api.nasa.gov/",
        "url": "https://api.nasa.gov/planetary/apod",
        "params": {"api_key": "DEMO_KEY"},
        "uso": "Astronomy Picture of the Day. Señal visual + metadatos espaciales.",
    },
    {
        "id": 26,
        "name": "NASA NeoWs",
        "category": "ciencia",
        "auth": "demo_key",
        "docs": "https://api.nasa.gov/",
        "url": "https://api.nasa.gov/neo/rest/v1/feed/today",
        "params": {"api_key": "DEMO_KEY"},
        "uso": "Asteroides cercanos hoy. Pronóstico de objetos NEO.",
    },
    {
        "id": 27,
        "name": "Open Notify ISS",
        "category": "ciencia",
        "auth": "none",
        "docs": "http://open-notify.org/Open-Notify-API/",
        "url": "http://api.open-notify.org/iss-now.json",
        "params": {},
        "uso": "Posición en vivo de la ISS.",
    },
    {
        "id": 28,
        "name": "SpaceX Next Launch",
        "category": "ciencia",
        "auth": "none",
        "docs": "https://github.com/r-spacex/SpaceX-API",
        "url": "https://api.spacexdata.com/v5/launches/next",
        "params": {},
        "uso": "Próximo lanzamiento. Evento predecible de alto impacto mediático.",
    },
    {
        "id": 29,
        "name": "Hacker News Top",
        "category": "noticias",
        "auth": "none",
        "docs": "https://github.com/HackerNews/API",
        "url": "https://hacker-news.firebaseio.com/v0/topstories.json",
        "params": {},
        "uso": "Señal de atención tech. Útil para tendencia de IA.",
    },
    {
        "id": 30,
        "name": "Hacker News Item",
        "category": "noticias",
        "auth": "none",
        "docs": "https://github.com/HackerNews/API",
        "url": "https://hacker-news.firebaseio.com/v0/item/1.json",
        "params": {},
        "uso": "Detalle de historia HN (se reemplaza el id en runtime).",
    },
    {
        "id": 31,
        "name": "Reddit WorldNews JSON",
        "category": "noticias",
        "auth": "none",
        "docs": "https://www.reddit.com/dev/api/",
        "url": "https://www.reddit.com/r/worldnews/top.json",
        "params": {"limit": 5, "t": "day"},
        "uso": "Titulares globales del día para contexto de pronóstico.",
        "headers": {"User-Agent": "MenteMaestra/1.0"},
    },
    {
        "id": 32,
        "name": "GitHub Zen",
        "category": "developer",
        "auth": "none",
        "docs": "https://docs.github.com/en/rest",
        "url": "https://api.github.com/zen",
        "params": {},
        "uso": "Health-check de GitHub API pública.",
    },
    {
        "id": 33,
        "name": "GitHub Search Repos",
        "category": "developer",
        "auth": "none",
        "docs": "https://docs.github.com/en/rest/search",
        "url": "https://api.github.com/search/repositories",
        "params": {"q": "forecasting language:python stars:>100", "sort": "stars", "per_page": 3},
        "uso": "Descubre repos útiles para desarrollar IA de pronóstico.",
    },
    {
        "id": 34,
        "name": "npm Registry",
        "category": "developer",
        "auth": "none",
        "docs": "https://github.com/npm/registry/blob/main/docs/REGISTRY-API.md",
        "url": "https://registry.npmjs.org/axios",
        "params": {},
        "uso": "Metadatos de paquetes JS para stack de integración.",
    },
    {
        "id": 35,
        "name": "PyPI JSON",
        "category": "developer",
        "auth": "none",
        "docs": "https://warehouse.pypa.io/api-reference/json.html",
        "url": "https://pypi.org/pypi/httpx/json",
        "params": {},
        "uso": "Versiones y dependencias Python. Útil para agentes de código.",
    },
    {
        "id": 36,
        "name": "Open Library Search",
        "category": "conocimiento",
        "auth": "none",
        "docs": "https://openlibrary.org/developers/api",
        "url": "https://openlibrary.org/search.json",
        "params": {"q": "artificial intelligence", "limit": 3},
        "uso": "Libros abiertos para corpus y recomendaciones.",
    },
    {
        "id": 37,
        "name": "Gutendex",
        "category": "conocimiento",
        "auth": "none",
        "docs": "https://gutendex.com/",
        "url": "https://gutendex.com/books",
        "params": {"search": "intelligence"},
        "uso": "Project Gutenberg. Texto libre para preentrenamiento ligero.",
    },
    {
        "id": 38,
        "name": "Free Dictionary",
        "category": "nlp",
        "auth": "none",
        "docs": "https://dictionaryapi.dev/",
        "url": "https://api.dictionaryapi.dev/api/v2/entries/en/forecast",
        "params": {},
        "uso": "Definiciones y fonética. Capa léxica del cerebro.",
    },
    {
        "id": 39,
        "name": "Datamuse",
        "category": "nlp",
        "auth": "none",
        "docs": "https://www.datamuse.com/api/",
        "url": "https://api.datamuse.com/words",
        "params": {"ml": "forecast", "max": 8},
        "uso": "Sinónimos y palabras relacionadas. Expansión de queries.",
    },
    {
        "id": 40,
        "name": "MusicBrainz",
        "category": "media",
        "auth": "none",
        "docs": "https://musicbrainz.org/doc/MusicBrainz_API",
        "url": "https://musicbrainz.org/ws/2/artist/",
        "params": {"query": "reggaeton", "fmt": "json", "limit": 3},
        "uso": "Metadatos musicales abiertos. Útil para proyectos creativos R.M.P.",
        "headers": {"User-Agent": "MenteMaestra/1.0 (https://github.com/rmpsorva/mente-maestra)"},
    },
    {
        "id": 41,
        "name": "JSONPlaceholder",
        "category": "sandbox",
        "auth": "none",
        "docs": "https://jsonplaceholder.typicode.com/",
        "url": "https://jsonplaceholder.typicode.com/posts/1",
        "params": {},
        "uso": "API falsa estable para pruebas del cliente HTTP.",
    },
    {
        "id": 42,
        "name": "DummyJSON",
        "category": "sandbox",
        "auth": "none",
        "docs": "https://dummyjson.com/docs",
        "url": "https://dummyjson.com/products",
        "params": {"limit": 3},
        "uso": "Catálogo e-commerce de prueba para pipelines.",
    },
    {
        "id": 43,
        "name": "Random User",
        "category": "sandbox",
        "auth": "none",
        "docs": "https://randomuser.me/documentation",
        "url": "https://randomuser.me/api/",
        "params": {"results": 1, "nat": "us"},
        "uso": "Perfiles sintéticos para tests de UI y sesgo demográfico.",
    },
    {
        "id": 44,
        "name": "Agify",
        "category": "nlp",
        "auth": "none",
        "docs": "https://agify.io/",
        "url": "https://api.agify.io",
        "params": {"name": "rene"},
        "uso": "Estimación de edad por nombre. Feature demográfica.",
    },
    {
        "id": 45,
        "name": "Genderize",
        "category": "nlp",
        "auth": "none",
        "docs": "https://genderize.io/",
        "url": "https://api.genderize.io",
        "params": {"name": "rene"},
        "uso": "Estimación de género por nombre (probabilística).",
    },
    {
        "id": 46,
        "name": "Nationalize",
        "category": "nlp",
        "auth": "none",
        "docs": "https://nationalize.io/",
        "url": "https://api.nationalize.io",
        "params": {"name": "rene"},
        "uso": "Probable origen nacional del nombre.",
    },
    {
        "id": 47,
        "name": "PokeAPI",
        "category": "sandbox",
        "auth": "none",
        "docs": "https://pokeapi.co/docs/v2",
        "url": "https://pokeapi.co/api/v2/pokemon/pikachu",
        "params": {},
        "uso": "Grafo de entidades bien documentado para demos de RAG.",
    },
    {
        "id": 48,
        "name": "Numbers API",
        "category": "conocimiento",
        "auth": "none",
        "docs": "http://numbersapi.com/",
        "url": "http://numbersapi.com/42",
        "params": {"json": True},
        "uso": "Hechos numéricos. Útil para prompts y curiosidad.",
    },
    {
        "id": 49,
        "name": "Official Joke API",
        "category": "sandbox",
        "auth": "none",
        "docs": "https://github.com/15Dkatz/official_joke_api",
        "url": "https://official-joke-api.appspot.com/random_joke",
        "params": {},
        "uso": "Texto corto estructurado para tests de generación.",
    },
    {
        "id": 50,
        "name": "Advice Slip",
        "category": "sandbox",
        "auth": "none",
        "docs": "https://api.adviceslip.com/",
        "url": "https://api.adviceslip.com/advice",
        "params": {},
        "uso": "Frase breve. Latido del sistema y demo de resiliencia HTTP.",
    },
]

CATEGORIES = sorted({a["category"] for a in APIS})


def get(api_id: int) -> dict:
    for api in APIS:
        if api["id"] == api_id:
            return api
    raise KeyError(f"API id {api_id} no existe")


def by_category(category: str) -> list:
    return [a for a in APIS if a["category"] == category]
