"""Oleada 2: APIs extra con señal nueva (ids 51-100).

Criterio: sin clave (o DEMO), dato que el núcleo 1-50 no cubría,
y útil para pronosticar o desarrollar IA. Nada de sandbox de relleno.
"""

EXTRA = [
    {"id": 51, "name": "Open-Meteo Elevation", "category": "geo", "auth": "none",
     "docs": "https://open-meteo.com/en/docs/elevation-api",
     "url": "https://api.open-meteo.com/v1/elevation", "params": {"latitude": 29.76, "longitude": -95.37},
     "uso": "Altitud para modelos de clima, solar y salud respiratoria."},
    {"id": 52, "name": "Open-Meteo Flood", "category": "clima", "auth": "none",
     "docs": "https://open-meteo.com/en/docs/flood-api",
     "url": "https://flood-api.open-meteo.com/v1/flood", "params": {"latitude": 29.76, "longitude": -95.37, "daily": "river_discharge"},
     "uso": "Caudal de río. Riesgo de inundación para Houston y logística."},
    {"id": 53, "name": "Open-Meteo Marine", "category": "clima", "auth": "none",
     "docs": "https://open-meteo.com/en/docs/marine-weather-api",
     "url": "https://marine-api.open-meteo.com/v1/marine", "params": {"latitude": 29.3, "longitude": -94.8, "current": "wave_height,sea_surface_temperature"},
     "uso": "Oleaje y temperatura del Golfo. Puerto de Houston / energía offshore."},
    {"id": 54, "name": "NWS alerts", "category": "clima", "auth": "none",
     "docs": "https://www.weather.gov/documentation/services-web-api",
     "url": "https://api.weather.gov/alerts/active", "params": {"point": "29.76,-95.37"},
     "headers": {"User-Agent": "MenteMaestra/1.2 (github.com/rmpsorva/mente-maestra)", "Accept": "application/geo+json"},
     "uso": "Alertas oficiales NOAA para Texas. Señal de emergencia."},
    {"id": 55, "name": "UK Carbon Intensity", "category": "energia", "auth": "none",
     "docs": "https://carbon-intensity.github.io/api-definitions/",
     "url": "https://api.carbonintensity.org.uk/intensity", "params": {},
     "uso": "gCO2/kWh de la red. Proxy de mix eléctrico y horario óptimo de carga."},
    {"id": 56, "name": "Open-Meteo Historical", "category": "clima", "auth": "none",
     "docs": "https://open-meteo.com/en/docs/historical-weather-api",
     "url": "https://archive-api.open-meteo.com/v1/archive", "params": {"latitude": 29.76, "longitude": -95.37, "start_date": "2026-08-01", "end_date": "2026-08-07", "daily": "temperature_2m_max"},
     "uso": "Serie histórica para entrenar y validar pronósticos."},
    {"id": 57, "name": "OpenSky States", "category": "transito", "auth": "none",
     "docs": "https://openskynetwork.github.io/opensky-api/",
     "url": "https://opensky-network.org/api/states/all", "params": {"lamin": 29.3, "lomin": -95.8, "lamax": 30.2, "lomax": -94.8},
     "uso": "Tráfico aéreo vivo sobre Houston. Feature de actividad económica."},
    {"id": 58, "name": "OSRM route", "category": "transito", "auth": "none",
     "docs": "https://project-osrm.org/docs/v5.24.0/api/",
     "url": "https://router.project-osrm.org/route/v1/driving/-95.37,29.76;-95.36,29.75", "params": {"overview": "false"},
     "uso": "Ruta y duración OSM. Logística y ETA sin Google."},
    {"id": 59, "name": "Nager Date US", "category": "gobierno", "auth": "none",
     "docs": "https://date.nager.at/swagger/index.html",
     "url": "https://date.nager.at/api/v3/PublicHolidays/2026/US", "params": {},
     "uso": "Feriados USA. Ajusta demanda, tráfico y mercado."},
    {"id": 60, "name": "World Time Houston", "category": "datos", "auth": "none",
     "docs": "https://worldtimeapi.org/",
     "url": "https://worldtimeapi.org/api/timezone/America/Chicago", "params": {},
     "uso": "Reloj oficial + DST. Ancla temporal de todo pronóstico."},
    {"id": 61, "name": "OpenFDA drug events", "category": "salud", "auth": "none",
     "docs": "https://open.fda.gov/apis/",
     "url": "https://api.fda.gov/drug/event.json", "params": {"search": "patient.drug.medicinalproduct:metformin", "limit": 1},
     "uso": "Eventos adversos FDA. Señal farmacovigilancia."},
    {"id": 62, "name": "ClinicalTrials search", "category": "salud", "auth": "none",
     "docs": "https://clinicaltrials.gov/data-api/api",
     "url": "https://clinicaltrials.gov/api/v2/studies", "params": {"query.term": "diabetes", "pageSize": 3},
     "uso": "Ensayos clínicos vivos. Pipeline de salud e IA médica."},
    {"id": 63, "name": "WHO GHO indicator list", "category": "salud", "auth": "none",
     "docs": "https://www.who.int/data/gho/info/gho-odata-api",
     "url": "https://ghoapi.azureedge.net/api/Indicator", "params": {"$top": 5},
     "uso": "Catálogo OMS. Indicadores globales de salud."},
    {"id": 64, "name": "Open Food Facts", "category": "salud", "auth": "none",
     "docs": "https://openfoodfacts.github.io/openfoodfacts-server/api/",
     "url": "https://world.openfoodfacts.org/api/v2/product/737628064502.json", "params": {},
     "uso": "Etiqueta nutricional abierta. Features para dieta/diabetes."},
    {"id": 65, "name": "Universities", "category": "datos", "auth": "none",
     "docs": "https://github.com/Hipo/university-domains-list",
     "url": "http://universities.hipolabs.com/search", "params": {"name": "Houston"},
     "uso": "Universidades por ciudad. Red de talento y papers."},
    {"id": 66, "name": "USGS elevation", "category": "geo", "auth": "none",
     "docs": "https://epqs.nationalmap.gov/v1/docs",
     "url": "https://epqs.nationalmap.gov/v1/json", "params": {"x": -95.37, "y": 29.76, "wkid": 4326, "units": "Meters"},
     "uso": "Cota oficial USGS. Inundación y solar."},
    {"id": 67, "name": "Wikimedia pageviews", "category": "noticias", "auth": "none",
     "docs": "https://wikitech.wikimedia.org/wiki/Analytics/AQS/Pageviews",
     "url": "https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia/all-access/all-agents/Bitcoin/daily/20260801/20260807", "params": {},
     "uso": "Atención pública a un tema. Feature de sentimiento/atención."},
    {"id": 68, "name": "Launch Library 2", "category": "ciencia", "auth": "none",
     "docs": "https://thespacedevs.com/llapi",
     "url": "https://ll.thespacedevs.com/2.2.0/launch/upcoming/", "params": {"limit": 3},
     "uso": "Próximos lanzamientos globales, no solo SpaceX."},
    {"id": 69, "name": "Where The ISS At", "category": "ciencia", "auth": "none",
     "docs": "https://wheretheiss.at/w/developer",
     "url": "https://api.wheretheiss.at/v1/satellites/25544", "params": {},
     "uso": "ISS con velocidad y altitud. Mejor que Open Notify."},
    {"id": 70, "name": "Mempool.space hashrate", "category": "crypto", "auth": "none",
     "docs": "https://mempool.space/docs/api/rest",
     "url": "https://mempool.space/api/v1/mining/hashrate/3d", "params": {},
     "uso": "Hashrate BTC. Salud de la red, no solo precio."},
    {"id": 71, "name": "Mempool fees", "category": "crypto", "auth": "none",
     "docs": "https://mempool.space/docs/api/rest",
     "url": "https://mempool.space/api/v1/fees/recommended", "params": {},
     "uso": "Fees recomendados. Congestión on-chain."},
    {"id": 72, "name": "Fear and Greed", "category": "crypto", "auth": "none",
     "docs": "https://alternative.me/crypto/fear-and-greed-index/",
     "url": "https://api.alternative.me/fng/", "params": {"limit": 2},
     "uso": "Índice miedo/codicia. Régimen de sentimiento."},
    {"id": 73, "name": "CoinGecko global", "category": "crypto", "auth": "none",
     "docs": "https://docs.coingecko.com/reference/crypto-global",
     "url": "https://api.coingecko.com/api/v3/global", "params": {},
     "uso": "Cap total y dominio BTC. Contexto de ciclo."},
    {"id": 74, "name": "Stooq AAPL", "category": "finanzas", "auth": "none",
     "docs": "https://stooq.com/q/d/",
     "url": "https://stooq.com/q/l/", "params": {"s": "aapl.us", "f": "sd2t2ohlcv", "h": "", "e": "csv"},
     "uso": "Acción USA EOD sin clave. Ancla equity vs crypto."},
    {"id": 75, "name": "World Bank unemployment", "category": "economia", "auth": "none",
     "docs": "https://datahelpdesk.worldbank.org/knowledgebase/articles/889392",
     "url": "https://api.worldbank.org/v2/country/USA/indicator/SL.UEM.TOTL.ZS", "params": {"format": "json", "per_page": 3},
     "uso": "Desempleo USA. Feature macro de ciclo."},
    {"id": 76, "name": "IMF Dataflow", "category": "economia", "auth": "none",
     "docs": "https://data.imf.org/",
     "url": "https://dataservices.imf.org/REST/SDMX_JSON.svc/Dataflow", "params": {},
     "uso": "Catálogo FMI. Puerta a WEO y BOP."},
    {"id": 77, "name": "MyMemory translate", "category": "nlp", "auth": "none",
     "docs": "https://mymemory.translated.net/doc/spec.php",
     "url": "https://api.mymemory.translated.net/get", "params": {"q": "forecast", "langpair": "en|es"},
     "uso": "Traducción gratis. El cerebro habla ES/EN."},
    {"id": 78, "name": "LibreTranslate detect", "category": "nlp", "auth": "none",
     "docs": "https://libretranslate.com/docs",
     "url": "https://libretranslate.com/languages", "params": {},
     "uso": "Idiomas disponibles para capa bilingüe R.M.P."},
    {"id": 79, "name": "iTunes Search", "category": "media", "auth": "none",
     "docs": "https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/iTuneSearchAPI/index.html",
     "url": "https://itunes.apple.com/search", "params": {"term": "reggaeton", "entity": "song", "limit": 3},
     "uso": "Catálogo musical comercial. Señal para el proyecto R.M.P."},
    {"id": 80, "name": "Deezer search", "category": "media", "auth": "none",
     "docs": "https://developers.deezer.com/api",
     "url": "https://api.deezer.com/search", "params": {"q": "reggaeton", "limit": 3},
     "uso": "Tracks y artistas Deezer sin OAuth para descubrimiento."},
    {"id": 81, "name": "Lyrics.ovh", "category": "media", "auth": "none",
     "docs": "https://lyricsovh.docs.apiary.io/",
     "url": "https://api.lyrics.ovh/v1/Coldplay/Yellow", "params": {},
     "uso": "Letra pública. Corpus para análisis de canciones."},
    {"id": 82, "name": "TheSportsDB test", "category": "deporte", "auth": "none",
     "docs": "https://www.thesportsdb.com/api.php",
     "url": "https://www.thesportsdb.com/api/v1/json/3/searchteams.php", "params": {"t": "Houston"},
     "uso": "Equipos de Houston. Eventos locales que mueven tráfico."},
    {"id": 83, "name": "Open Brewery Houston", "category": "datos", "auth": "none",
     "docs": "https://www.openbrewerydb.org/documentation",
     "url": "https://api.openbrewerydb.org/v1/breweries", "params": {"by_city": "houston", "per_page": 3},
     "uso": "Actividad local de ocio. Proxy de demanda urbana."},
    {"id": 84, "name": "TVmaze schedule", "category": "media", "auth": "none",
     "docs": "https://www.tvmaze.com/api",
     "url": "https://api.tvmaze.com/schedule", "params": {"country": "US"},
     "uso": "Parrilla TV USA. Atención mediática del día."},
    {"id": 85, "name": "Archive.org search", "category": "conocimiento", "auth": "none",
     "docs": "https://archive.org/developers/search.html",
     "url": "https://archive.org/advancedsearch.php", "params": {"q": "artificial intelligence", "fl[]": "identifier,title", "output": "json", "rows": 3},
     "uso": "Corpus histórico. RAG con fuentes primarias."},
    {"id": 86, "name": "Wayback available", "category": "conocimiento", "auth": "none",
     "docs": "https://archive.org/help/wayback_api.php",
     "url": "https://archive.org/wayback/available", "params": {"url": "https://open-meteo.com"},
     "uso": "Si una fuente cae, busca snapshot. Resiliencia del cerebro."},
    {"id": 87, "name": "Hugging Face models", "category": "investigacion", "auth": "none",
     "docs": "https://huggingface.co/docs/hub/api",
     "url": "https://huggingface.co/api/models", "params": {"search": "forecasting", "limit": 3, "sort": "downloads"},
     "uso": "Modelos listos para forecasting. Atajo a desarrollar IA."},
    {"id": 88, "name": "Papers with Code", "category": "investigacion", "auth": "none",
     "docs": "https://paperswithcode.com/api/v1/docs/",
     "url": "https://paperswithcode.com/api/v1/papers/", "params": {"q": "time series", "items_per_page": 3},
     "uso": "Paper + código. El puente investigación → implementación."},
    {"id": 89, "name": "OpenAlex concepts", "category": "investigacion", "auth": "none",
     "docs": "https://docs.openalex.org/api-entities/concepts",
     "url": "https://api.openalex.org/concepts", "params": {"search": "forecasting", "per_page": 3},
     "uso": "Taxonomía científica. Enruta el conocimiento."},
    {"id": 90, "name": "Crossref funders", "category": "investigacion", "auth": "none",
     "docs": "https://www.crossref.org/documentation/retrieve-metadata/rest-api/",
     "url": "https://api.crossref.org/funders", "params": {"query": "energy", "rows": 3},
     "uso": "Quién financia qué. Mapa de incentivos de I+D."},
    {"id": 91, "name": "GitHub events public", "category": "developer", "auth": "none",
     "docs": "https://docs.github.com/en/rest/activity/events",
     "url": "https://api.github.com/events", "params": {},
     "uso": "Pulso global de código. Qué se está construyendo ahora."},
    {"id": 92, "name": "PyPI search simple", "category": "developer", "auth": "none",
     "docs": "https://warehouse.pypa.io/api-reference/json.html",
     "url": "https://pypi.org/pypi/scikit-learn/json", "params": {},
     "uso": "Versión de sklearn. Stack de forecasting clásico."},
    {"id": 93, "name": "crt.sh Tesla", "category": "seguridad", "auth": "none",
     "docs": "https://crt.sh/",
     "url": "https://crt.sh/", "params": {"q": "open-meteo.com", "output": "json"},
     "uso": "Certificados TLS. Salud e historial de un dominio fuente."},
    {"id": 94, "name": "DNS over HTTPS", "category": "seguridad", "auth": "none",
     "docs": "https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-https/",
     "url": "https://cloudflare-dns.com/dns-query", "params": {"name": "api.open-meteo.com", "type": "A"},
     "headers": {"Accept": "application/dns-json"},
     "uso": "Resolución DNS de fuentes. Detecta caídas reales."},
    {"id": 95, "name": "URLhaus recent", "category": "seguridad", "auth": "none",
     "docs": "https://urlhaus-api.abuse.ch/",
     "url": "https://urlhaus-api.abuse.ch/v1/urls/recent/", "params": {},
     "uso": "URLs maliciosas recientes. Higiene antes de seguir un link."},
    {"id": 96, "name": "Have I Been Pwned range sample", "category": "seguridad", "auth": "none",
     "docs": "https://haveibeenpwned.com/API/v3#PwnedPasswords",
     "url": "https://api.pwnedpasswords.com/range/21BD1", "params": {},
     "uso": "K-anonimato de passwords. Utilidad de seguridad personal."},
    {"id": 97, "name": "Open Library subject", "category": "conocimiento", "auth": "none",
     "docs": "https://openlibrary.org/dev/docs/api/subjects",
     "url": "https://openlibrary.org/subjects/forecasting.json", "params": {"limit": 3},
     "uso": "Libros por materia forecasting. Corpus dirigido."},
    {"id": 98, "name": "Wikidata search", "category": "conocimiento", "auth": "none",
     "docs": "https://www.wikidata.org/wiki/Wikidata:Data_access",
     "url": "https://www.wikidata.org/w/api.php", "params": {"action": "wbsearchentities", "search": "Houston", "language": "en", "format": "json"},
     "uso": "Grafo de entidades. Desambigua lugares y conceptos."},
    {"id": 99, "name": "REST Countries Mexico", "category": "datos", "auth": "none",
     "docs": "https://restcountries.com/",
     "url": "https://restcountries.com/v3.1/name/mexico", "params": {"fields": "name,capital,population,currencies,region"},
     "uso": "Perfil MX. Contexto para COP/MXN y diáspora."},
    {"id": 100, "name": "Open-Meteo Geocoding", "category": "geo", "auth": "none",
     "docs": "https://open-meteo.com/en/docs/geocoding-api",
     "url": "https://geocoding-api.open-meteo.com/v1/search", "params": {"name": "Houston", "count": 1},
     "uso": "Geocoder propio de Open-Meteo. Backup de Nominatim."},
]
